### ISSUE TITLE
.gitignore does not ignore received files

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.Python.StarterProject#7]
Hello,

I used this project this morning, and found that files such as `ConversionTests.test_full_conversion.received.md` were not being ignored.

This is the fix, if you wanted to copy it to this project:

https://github.com/claremacrae/jekyll_to_obsidian_publish/commit/28abac71719d8b443da581e4e9f33d68696ac84a

Note that there are two required changes:

- Fix the spelling
- Add the initial `*.`

It might also be worth checking all the other projects in https://github.com/approvals

**Comment by isidore** [comment]
thanks, fixed
